version: "3.7"
 
services: 
 
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - ./database/dbdata:/var/lib/mysql:rw
      - ./database:/docker-entrypoint-initdb.d
      #- ./database/ufabet.sql:/:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
    - '3306:3306'
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=1688XdAs
      - TZ=Asia/Bangkok
    networks:
      - proxy-net

  pma:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
        - "8181:80"
    env_file: .env
    depends_on:
        - db
    environment:
        - PMA_HOST=db
    networks:
      - proxy-net

networks:
  proxy-net:
      name: app-net
      external: true